language: php

env:
  - CI_VERSION=3.0.0
  
php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: 5.5
  fast_finish: true

before_install:
  - wget https://github.com/bcit-ci/CodeIgniter/archive/$CI_VERSION.tar.gz -O - | tar xz
  - cp -r application/* CodeIgniter-$CI_VERSION/application/
  - cp -r system/* CodeIgniter-$CI_VERSION/system/
  
install:
  - cp -r CodeIgniter-$CI_VERSION/system/* system/
  - cp -r CodeIgniter-$CI_VERSION/application/* application/
  - mv CodeIgniter-$CI_VERSION/index.php index.php
  - rm -rf CodeIgniter-$CI_VERSION

script:
  - phpunit
  - phpunit -c phpunit.xml
  
notifications:
    on_success: never
    on_failure: always
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
